# Generated by Django 5.2.3 on 2025-06-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seumodelo',
            old_name='munic',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='seumodelo',
            old_name='uf',
            new_name='estado',
        ),
    ]
